### ISSUE TITLE
Lost Amazon Alexa Devices. 

### ISSUE THREAD

**Issue by jsf1993** [IndigoDomotics/alexa-hue-bridge#10]
Was using the old plug in with Indigo 6 for a long time without issue.  Today, all of my devices stopped working with Alexa.  Thought I could solve the problem by upgrading to Indigo 7 and the most up to date Alexa plugin.  Still not working. My devices are all offline and Alexa will not discover them.  I have tried repeatedly.  Restarted my IMac, etc.  no dice. Please help!

Thanks!

**Comment by autolog** [comment]
Please post a request for help in the Indigo Alexa-Hue Bridge Support forum. Not only will you get a reply from me but also other users can help as well.:)

Alexa-Hue Bridge forum is at http://forums.indigodomo.com/viewforum.php?f=208

**Comment by autolog** [comment]
I assume that this has been resolved - if not please re-open. :)
