### ISSUE TITLE
Responder startup failed because host address is not available.

### ISSUE THREAD

**Issue by ichrispod** [IndigoDomotics/alexa-hue-bridge#14]
Hi Guys...  trying to set this up.  When I enable Discovery Mode I get the following...

Mar 4, 2018 at 10:36:10 AM
   Reloading plugin "Alexa-Hue Bridge 3.0.20"
   Stopping plugin "Alexa-Hue Bridge 3.0.20" (pid 552)
   Alexa-Hue Bridge                Alexa-Hue Bridge shutdown requested
   Stopped plugin "Alexa-Hue Bridge 3.0.20"
   Starting plugin "Alexa-Hue Bridge 3.0.20" (pid 594)
   Alexa-Hue Bridge                Alexa-Hue Bridge initialising . . .
   Alexa-Hue Bridge                Plugin Host IP Address is discovered as: '100.19.60.117'
   Alexa-Hue Bridge                Alexa discovery request logging enabled
   Alexa-Hue Bridge Warning        Debugging enabled for Alexa-Hue Bridge: General, Server, Broadcaster, Responder, Method Trace
   Started plugin "Alexa-Hue Bridge 3.0.20"
   Alexa-Hue Bridge                Alexa-Hue Bridge initialization complete
   Alexa-Hue Bridge                'Alexia' has one Alexa Device published
   Alexa-Hue Bridge                Starting Hue Bridge 'Alexia' web server thread
   Alexa-Hue Bridge                Starting Hue Bridge 'Alexia' discovery thread as 'Auto Start Discovery' requested
  :exclamation: Alexa-Hue Bridge Error          'Alexia' Responder startup failed because host address is not available.
   :exclamation:Alexa-Hue Bridge Error          Double check that the host is specified correctly in the Plugin Config. Correct if invalid and then reload the plugin.
   Alexa-Hue Bridge                Alexa-Hue Bridge 'Alexia' started: Host: 100.19.60.117 Port: 8180
   Alexa-Hue Bridge                Alexa-Hue Bridge checking network access by attempting to access 'www.google.com'
   Alexa-Hue Bridge                Alexa-Hue Bridge network access check to www.google.com successfully completed.
   Alexa-Hue Bridge                Alexa-Hue Bridge checking for Plugin update
   Alexa-Hue Bridge                Checking for updates...
   Alexa-Hue Bridge                No updates are available
   Alexa-Hue Bridge                Alexa-Hue Bridge next update check scheduled for: Monday, 2018-Mar-05 at 10:36

**Comment by autolog** [comment]
Haven't seen this one before.

Have you specified your external IP address as the host address? The plugin expects a local private IP address. Can you try specifying this in the plugin config?

**Comment by ichrispod** [comment]
Thanks, Jon.  I’ve tried with using the Auto and an Private address.  For giggles, I set the IP address of the Mac Mini that runs Indigo and wha-la! That error is gone! 

Chris

**Comment by autolog** [comment]
Great - glad it's sorted. Again it is useful feedback as the plugin ideally should pick up that it isn't a local address and complain about it. :)
