### ISSUE TITLE
International (Swedish) characters in device names not handled

### ISSUE THREAD

**Issue by glitz1** [IndigoDomotics/alexa-hue-bridge#16]
I have a few virtual devices with Swedish characters (åäöÅÄÖ).
If any of these characters are in the device name, I get the error below in the event log and the list of devices in the configuration dialogue in the "published alexa devices" is blank (no devices are shown). I have version 3.0.20 of the hue bridge and Indigo 7.1.1.

Please correct this, I really want to be able to use Swedish characters in the device names. I guess other characters (like for example German) will generate the same error.
---
Alexa-Hue Bridge Error          Error in plugin execution GetUiDynamicList:

Traceback (most recent call last):
  File "plugin.py", line 1541, in publishedAlexaDevicesList
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 7: ordinal not in range(128)

**Comment by FlyingDiver** [comment]
Please try pre-release 3.0.29:  https://github.com/IndigoDomotics/alexa-hue-bridge/releases/tag/3.0.29

**Comment by glitz1** [comment]
Works like a charm! Thanks for the quick fix!
