### ISSUE TITLE
after our internet went down, alexa doesn't see the devices

### ISSUE THREAD

**Issue by barnman80** [IndigoDomotics/alexa-hue-bridge#17]
after our internet went down, alexa doesn't see the devices, I can't seem to get her to see my devices again

**Comment by autolog** [comment]
You haven't given me much to go ;)

For support please post a more detailed description of your problem in the Indigo Alexa-Hue-Bridge forum at https://forums.indigodomo.com/viewforum.php?f=208

Thanks :)
