### ISSUE TITLE
Project needs a license

### ISSUE THREAD

**Issue by nathanjw** [IndigoDomotics/alexa-hue-bridge#2]
Can the developers select a formal OSS license for this project? Something that allows commercial use without restriction (MIT or Apache licenses, say) is probably a good choice.

**Comment by indigodomo** [comment]
We've added an UNLICENSE to the project, which essentially makes the source completely free for any use. It's the most liberal license we could find.

**Comment by nathanjw** [comment]
Thanks, but my lawyer-type friends tell me that the Unlicense isn't very good (it's a "crayon license" not drafted by lawyers, it's not approved by major outfits like OSI (opensource.org), public domain doesn't make sense the way it's used here and is a problematic concept outside of the USA, etc.).

Github's http://choosealicense.com/ would seem to suggest the MIT license for this (and has the text for you to copy and paste) - simple, permissive, battle-tested, and (critically for me) already well-known and well-understood by software company lawyers. Can the project switch to that?

**Comment by indigodomo** [comment]
Our legal council is fine with it - he's not quite the OSI snob as many are. It's also included on Github's choose license (http://choosealicense.com/licenses/#unlicense). The only substantive difference is there is no requirement to include the notice (as the MIT license does). We've already spent enough time on this so we'll just leave it like it is.
