### ISSUE TITLE
Discovery cannot be enabled

### ISSUE THREAD

**Issue by epounds** [IndigoDomotics/alexa-hue-bridge#4]
Indigo version - 7.0.2
Alexa-Hue Bridge version - 2.0.2
Alexa devices - one Echo Dot on the same subnet as Indigo

I have set up the plugin with a single device (virtual device) to test it out. See attached screenshot.

Discovery is not on by default, even though the documentation says it should be. When I try to enable discovery, I get this error in the log:
**Alexa-Hue Bridge Error          Start Discovery action failed for 'Alexa': broadcaster thread couldn't start. Try restarting the plugin.**

I have tried reloading the plugin and changing the expiration setting to something greater than 0. These did not help. Any ideas what may be going wrong?

<img width="403" alt="screen shot 2016-11-29 at 12 14 20 pm" src="https://cloud.githubusercontent.com/assets/24256782/20727209/7c56dbee-b62d-11e6-9e14-03605ca5c827.png">

**Comment by autolog** [comment]
Not much to go on here unfortunately.
I think the plugin needs to be enhanced to provide some extra error info.

It might be worth trying a different port, say 8185 to see if the makes a difference?

Failing that, you can turn on debug logging for everything, stop and start the plugin, wait for the error and then PM me the log (user Autolog on the Indigo forums) and I will take a look. :)

Access the log via the Indigo Event Log, click on **Show Events Folder** and the file I need to see is **plugin.log** in folder **opensource.alexa-hue-bridge**

**Comment by bill4217192** [comment]
I am getting this error from the logs - any help or ideas?  In system preferences the computer does have a "name" in the sharing setting.  

 Alexa-Hue Bridge Error          Computer has no host name specified. Check the Sharing system preference and restart the plugin once the name is resolved.
   Alexa-Hue Bridge                'Hue name' has 2 devices published
   Alexa-Hue Bridge                Starting Hue Bridge 'Hue name' web server thread
   Alexa-Hue Bridge                Starting Hue Bridge 'Hue name' discovery threads as 'Auto Start Discovery' requested
   Alexa-Hue Bridge Error          StandardError detected in Responder.Run for 'Hue name'. Line '166' has error='must be string, not None'

**Comment by epounds** [comment]
This resolved the issue. Thank you! My server had a host name, but when I changed it, an issue must have been resolved because the plugin started working.
