### ISSUE TITLE
Discovery of Action groups

### ISSUE THREAD

**Issue by foriegnbody** [IndigoDomotics/alexa-hue-bridge#5]
While it's great to have a plugin to expose devices (I was using a fork of hueAndMe) it would be excellent to expose Action Groups also. 

That would allow actions like 'Alexa, turn on ALL LIGHTS'.

Any chance that's on your 'todo' list?!

**Comment by foriegnbody** [comment]
Actually you could do this with a virtual device correct?
If so please close this issue ;-)

**Comment by nathanjw** [comment]
You can do this with a virtual device - I do exactly this to trigger an action to turn on a cat feeder (and then turn it off 30 seconds later).

**Comment by indigodomo** [comment]
Yep, a Virtual Device is definitely the way to go here.
