### ISSUE TITLE
Echo for Christmas - Cannot discover published devices

### ISSUE THREAD

**Issue by whmoorejr** [IndigoDomotics/alexa-hue-bridge#6]
This Echo is a Christmas gift for my wife and hidden in my office.  I'm really hoping to get this figured out before I give it to her.

Running Indigo 7.02 and Alexa-Hue 2.0.2 (no prior use of this plugin)
Fresh plugin install.  Created device "LightsAndFans", added & published 7 lights/fans.  
Port was set to "Auto" and it switched to 8178 (which is how it is set now)
Expiration was 5, then tried 0, then on 3, now trying 0 again
Have 7 devices (5 lights, 2 fans) published
When in 'Discovery Mode', Alexa doesn't detect.
When I ask Alexa to detect, I've used verbal commands, the iOS app and web app.  No luck.

Getting two event log errors:
1) Computer has no host name specified. Check the Sharing system preference and restart the plugin once the name is resolved.

2) StandardError detected in Responder.Run for 'LightsAndFans'. Line '166' has error='must be string, not None'   (LightsAndFans is the name of my Alexa-Hue device)

Spent a full day yesterday attempting to resolve the "host name" issue to no avail.

Using Terminal: sudo lsof -i :1900  (Plex is running.  I exit Plex before attempting to 'Discover')

From Indigo Scripting Shell:
>>> import socket
>>> socket.gethostbyname(socket.gethostname())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
gaierror: [Errno 8] nodename nor servname provided, or not known
>>> socket.gethostname()
'WHM-Server'

From Preferences: 
Checked Services: File, Login, Management, Apple Events
Computer Name: WHM-Server
Local Hostname: WHM-Server.local
Use dynamic global hostname - not checked

Any help or suggestions would be great.

**Comment by whmoorejr** [comment]
[plugin.log.zip](https://github.com/IndigoDomotics/alexa-hue-bridge/files/634349/plugin.log.zip)
Had to zip it... wouldn't let me attach a .log file.

**Comment by indigodomo** [comment]
This problem is generally caused by an OS install that at some point had Mac OS X Server installed. I'm not sure if there's ever been a definitive solution, but [this post](http://forums.indigodomo.com/viewtopic.php?p=121235#p121235) may help. Unfortunately, I've never replicated this issue myself so I'm just relying on others that have had the problem.

**Comment by indigodomo** [comment]
[Here's another post](http://forums.indigodomo.com/viewtopic.php?p=121641#p121641) that might help.

**Comment by whmoorejr** [comment]
I use to have Mac OS X Server on my old mac mini running indigo.  Too many issues and OS X Server never would act right.  I got a new Mac Mini about 2 years ago running Yosemite.  I may have upgraded to El Capitan then put it back to Yosemite (I was having an issue with El Capitan not letting the Mini auto log in after a power failure).  

Anyway, I transferred Indigo from my old Mac Mini to my new Mac Mini.

No OS X Server has ever been on my current Mac.  (I call it WHM-Server because all it does is run programs that serve: Plex, Indigo, iTunes, etc.... no actual server os or server app running).

Could this be a leftover something inside indigo that made it through the transfer between computers and between the transfer between Indigo v6 and now Indigo v7?

I looked at both the posts you sent... both are pointing at a DNS issue.

Without running OS X Server or Server App, my only DNS option on my computer is under Network: Advanced: DNS  Where DNS Servers: 10.0.6.1 (my Airport Extreme) and Search Domains: hsd1.tx.comcast.net (My ISP)

If it is a DNS something on my Mini that somehow made it over to this computer, I don't know where to look.  

FYI: I've pretty much been through all of the Alexa-Hue posts looking for answers and some posts from other forums on Hostnames.

I tried this terminal approach to resolving as well (don't remember what website I found it at)
COMPUTER_NAME=WHM-Server
sudo scutil --set ComputerName $COMPUTER_NAME
sudo scutil --set HostName $COMPUTER_NAME
sudo scutil --set LocalHostName $COMPUTER_NAME
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $COMPUTER_NAME

My only thought on the above.... did I need to put the ".local" onto one of those lines?

Tried another terminal approach that (supposedly) turns off bonjour then turns it back on and that could re-post your ".local" to the network?

I say "Supposedly" because I am scared stupid to use terminal commands.  For me I am blindly cutting and pasting hoping it works and that it doesn't break something else in the process.

**Comment by indigodomo** [comment]
"Could this be a leftover something inside indigo that made it through the transfer between computers and between the transfer between Indigo v6 and now Indigo v7?"

This has nothing to do with Indigo, it's a completely separate issue, so if the only thing you moved over to the new Mac was Indigo then there shouldn't be any left-over Mac OS X Server cruft. And, unfortunately, I have no answers since I've never experienced the issue nor can I reproduce it.

You might try removing your ISP from the search domains list - that really shouldn't be there anyway. Reboot after you do that just to make sure your Mac gets the message.

**Comment by whmoorejr** [comment]
Then I have one idea.... The new mac was the replacement to my old mac (which was running OS X Server and Server App).  When I started up the new Mac, I selected the "Replacing an existing Mac" instead of "This is a new machine" (Paraphrasing, I don't recall the exact options).  

I did this so that I would minimize the amount of configuring I would have to do later to get everything back up and running as soon as possible.  

Maybe that is how some of the "Server OS / Server App" bits are on the new Mac?

My solution: Start over.  Format / Clean Install of Yosemite.  Re-install programs, etc and go from there.

My to-do list is now: collecting software keys and I have to figure out how to back-up my Indigo configuration.  (I literally took a month of work just to build my initial indigo configuration.... I'm not doing that again)

Tips / Suggestions?  Does it sound like I might be on the right track?

**Comment by indigodomo** [comment]
Yep, I suspect that's exactly what happened. Starting from scratch would be a safer process. Moving an [Indigo install to another Mac](http://wiki.indigodomo.com/doku.php?id=indigo_7_documentation:getting_started#moving_an_indigo_7_installation_to_another_mac) is quite straight-forward. If you didn't upgrade to Indigo 7 on your old Mac, then [migrate your Indigo 6 install over](http://wiki.indigodomo.com/doku.php?id=indigo_6_documentation:getting_started#moving_an_indigo_6_installation_to_another_mac) first then install Indigo 7.
