### ISSUE TITLE
Computer has no host name specified

### ISSUE THREAD

**Issue by bill4217192** [IndigoDomotics/alexa-hue-bridge#7]
I am getting the following error on loading of the plug in.  Computer appears to have a name and sharing is standard settings.

Alexa-Hue Bridge Error          Computer has no host name specified. Check the Sharing system preference and restart the plugin once the name is resolved.
   Alexa-Hue Bridge                'Hue name' has 2 devices published
   Alexa-Hue Bridge                Starting Hue Bridge 'Hue name' web server thread
   Alexa-Hue Bridge                Starting Hue Bridge 'Hue name' discovery threads as 'Auto Start Discovery' requested
   Alexa-Hue Bridge Error          StandardError detected in Responder.Run for 'Hue name'. Line '166' has error='must be string, not None'

**Comment by bill4217192** [comment]
In my case this was due to some issue with OS X Server.  Reading all previous posts (on the forum not here), I eventually resolved it, but to be honest not sure the sequence or actual solution.  The Server app had an alert that needed me to click "resolve" on the "Local host name mismatch".  After that it worked.

**Comment by indigodomo** [comment]
For more simple diagnostics of this specific issue, I've moved all the related posts into a single topic on the forums. http://forums.indigodomo.com/viewtopic.php?p=110012#p110012
