### ISSUE TITLE
Alexa-Hue not showing up as option when creating new device

### ISSUE THREAD

**Issue by ChopOMatic** [IndigoDomotics/alexa-hue-bridge#8]
I'm running the latest release of Indigo v7, but when I create a new device, Alexa-Hue is not among the type options. The plugin is installed and enabled. When I go to MANAGE PLUGINS, it's in the list and its box is checked. Any ideas?

**Comment by evansgo** [comment]
You'd be much better off asking in the indigo forum, you'll get more answers . But if I remember correctly you need new virtual device, not new device - then you select Alexa-hue

**Comment by ChopOMatic** [comment]
Thx!

**Comment by autolog** [comment]
What version of the plugin are you running?

**Comment by ChopOMatic** [comment]
Sorry for the slow reply. Running 1.0.3.




Jerry Hatchett, CCE, EnCE

Certified Computer Examiner
EnCase Certified Examiner
Licensed Private Investigator (Texas PSB License #A18333)

Omni:  713-364-2467



DISCLAIMER:  Anything I say, particularly with regard to technology, should
be interpreted generally, not specifically. The online world is a wonderful
thing, but rarely is it practical to cover every imaginable scenario in a
written, fast-paced forum. There are often exceptions, so keep that in mind.

**Comment by ChopOMatic** [comment]
BTW, I had already run the update two or three times; for whatever reason, when I'd double-click the new plugin, I'd get a dialog saying the same version was already installed. When I realized just now that I was still running a really old version, I did an update again and this time it "took." :)
