### ISSUE TITLE
Error after restarting computer

### ISSUE THREAD

**Issue by Astroman** [IndigoDomotics/alexa-hue-bridge#9]
I recently converted to a faster server running Indigo and, for some reason, I'm getting errors from the plugin when I reboot the computer.: "Computer has no host name specified. Check the Sharing system preference and restart the plugin once the name is resolved" and "StandardError detected in Responder.Run for 'Alexa'. Line '175' has error='must be string, not None'"

If I then reload the plugin, all is OK. The host name is indeed specified in the Sharing pref, same as before. I'm speculating that the faster server is starting up the plugin before sharing is fully running but that is just a guess and I wouldn't know how to solve it anyway.

**Comment by Astroman** [comment]
I just noticed that a third error shows up in the log a little later in the startup process: "StandardError detected in Broadcaster.Run for 'Alexa'. Line '96' has error='[Errno 51] Network is unreachable'"

**Comment by autolog** [comment]
I will be releasing V3 before too long, so as discussed on the Indigo forum, we'll see if it occurs in V3.

**Comment by autolog** [comment]
I assume that this has been resolved. If not please re-open. :)
